---
Name: cmspreviewpreference
After: "framework/*", "cms/*"
---
UserPreviewPreference:
    DefaultMode: "content"

LeftAndMain:
    extensions:
        - "CMSPreviewPreference"

Member:
    extensions:
        - "UserPreviewPreference"